const permissions = {
    accessRoleDashboardPage: 'ACCESS_ROLE_DASHBOARD_PAGE',
    addNewRole: 'ADD_NEW_ROLE',
    updateRole: 'UPDATE_ROLE',
    removeRole: 'REMOVE_ROLE',
    accessCustomerDashboardPage: 'ACCESS_CUSTOMER_DASHBOARD_PAGE',
    deactivateCustomerAccount: 'DEACTIVATE_CUSTOMER_ACCOUNT',
    accessAdvisoryDashboardPage: 'ACCESS_ADVISORY_DASHBOARD_PAGE',
    chatWithCustomer: 'CHAT_WITH_CUSTOMER',
    accessStaffDashboardPage: 'ACCESS_STAFF_DASHBOARD_PAGE',
    addNewStaff: 'ADD_NEW_STAFF',
    updateStaffInformation: 'UPDATE_STAFF_INFORMATION',
    changeStaffRole: 'CHANGE_STAFF_ROLE',
    deactivateStaffAccount: 'DEACTIVATE_STAFF_ACCOUNT',
    modifyPersonalInformation: 'MODIFY_PERSONAL_INFORMATION',
    addNewShoeCategory: 'ADD_NEW_SHOE_CATEGORY',
    updateShoeCategory: 'UPDATE_SHOE_CATEGORY',
    deleteShoeCategory: 'DELETE_SHOE_CATEGORY',
    addNewProduct: 'ADD_NEW_PRODUCT',
    updateProductInformation: 'UPDATE_PRODUCT_INFORMATION',
    updateProductPrice: 'UPDATE_PRODUCT_PRICE',
    deleteProduct: 'DELETE_PRODUCT',
    accessOrderDashboardPage: 'ACCESS_ORDER_DASHBOARD_PAGE',
    processOrder: 'PROCESS_ORDER',
    accessImportDashboardPage: 'ACCESS_IMPORT_DASHBOARD_PAGE',
    addNewImport: 'ADD_NEW_IMPORT',
    accessPromotionDashboardPage: 'ACCESS_PROMOTION_DASHBOARD_PAGE',
    addNewPromotion: 'ADD_NEW_PROMOTION',
    updatePromotion: 'UPDATE_PROMOTION',
    disablePromotion: 'DISABLE_PROMOTION',
    accessCouponDashboardPage: 'ACCESS_COUPON_DASHBOARD_PAGE',
    addNewCoupon: 'ADD_NEW_COUPON',
    updateCoupon: 'UPDATE_COUPON',
    disableCoupon: 'DISABLE_COUPON',
    accessInventoryDashboardPage: 'ACCESS_INVENTORY_DASHBOARD_PAGE',
    accessDamageReportDashboardPage: 'ACCESS_DAMAGE_REPORT_DASHBOARD_PAGE',
    addNewDamageReport: 'ADD_NEW_DAMAGE_REPORT',
    updateDamageReport: 'UPDATE_DAMAGE_REPORT',
    accessProductStatisticPage: 'ACCESS_PRODUCT_STATISTIC_PAGE',
    accessRevenueStatisticPage: 'ACCESS_REVENUE_STATISTIC_PAGE'
} as const

export default permissions
