const ERROR_MESSAGES = {
    NO_CREDENTIALS: 'Không có thông tin xác thực.',
    INVALID_TOKEN: 'Token không hợp lệ',
    FORBIDDEN: 'Bạn không có quyền thực hiện hành động này.',
    BLOCKED_BY_CORS_POLICY: 'Bị chặn bởi chính sách bảo mật truy cập CORS.',
    INTERNAL_SERVER_ERROR: 'Lỗi không xác định từ phía server. Vui lòng thử lại sau.',
    INVALID_CREDENTIALS: 'Thông tin xác thực không hợp lệ.',
    NO_PERMISSION: 'Bạn không có quyền thực hiện hành động này.',
    USERNAME_EXISTED: 'Tên đăng nhập đã tồn tại.',
    EMAIL_EXISTED: 'Email đã tồn tại.',
    USER_NOT_FOUND: 'Người dùng không tồn tại.',
    INCORRECT_PASSWORD: 'Mật khẩu không chính xác.',
    INCORRECT_USERNAME_OR_PASSWORD: 'Tên đăng nhập hoặc mật khẩu không chính xác.',
    GOOGLE_AUTH_FAILED: 'Xác thực Google thất bại.',
    DATA_VALIDATION_FAILED: 'Dữ liệu không hợp lệ.',
    UPLOAD_IMAGE_FAILED: 'Tải ảnh lên thất bại.',
    DELETE_IMAGE_FAILED: 'Xóa ảnh thất bại.',
    EMAIL_VERIFICATION_FAILED: 'Email chưa được xác thực.',
    ROLE_NOT_FOUND: 'Không tìm thấy vai trò.',
    ROLE_EXISTED: 'Tên vai trò đã tồn tại.',
    ROLE_BEING_USED: 'Vai trò đang được sử dụng.',
    INVALID_ROLE_SELECTED: 'Không thể chọn vai trò này.',
    CATEGORY_NOT_FOUND: 'Không tìm thấy danh mục.',
    CATEGORY_EXISTED: 'Tên danh mục đã tồn tại.',
    CATEGORY_BEING_USED: 'Danh mục đang được sử dụng.',
    PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm.',
    PRODUCT_EXISTED: 'Tên sản phẩm đã tồn tại.',
    PRODUCT_ITEM_NOT_FOUND: 'Không tìm thấy chi tiết sản phẩm.',
    PRODUCT_IDS_MISMATCH: 'Các mã sản phẩm không khớp.',
    PRODUCT_BEING_USED: 'Sản phẩm đang được sử dụng.',
    PROMOTION_NOT_FOUND: 'Không tìm thấy chương trình khuyến mãi.',
    PROMOTION_EXISTED: 'Tên chương trình khuyến mãi đã tồn tại.',
    PROMOTION_BEING_USED: 'Chương trình khuyến mãi đang được sử dụng.',
    COUPON_NOT_FOUND: 'Không tìm thấy phiếu giảm giá.',
    COUPON_EXISTED: 'Tên phiếu giảm giá đã tồn tại.',
    COUPON_BEING_USED: 'Phiếu giảm giá đang được sử dụng.',
    DAMAGE_TYPE_NOT_FOUND: 'Không tìm thấy loại thiệt hại.',
    DAMAGE_TYPE_EXISTED: 'Tên loại thiệt hại đã tồn tại.',
    DAMAGE_TYPE_BEING_USED: 'Loại thiệt hại đang được sử dụng.',
    STORAGE_TYPE_NOT_FOUND: 'Không tìm thấy loại kho.',
    STORAGE_TYPE_EXISTED: 'Tên loại kho đã tồn tại.',
    STORAGE_TYPE_BEING_USED: 'Loại kho đang được sử dụng.',
    SUPPLIER_NOT_FOUND: 'Không tìm thấy nhà cung cấp.',
    SUPPLIER_EXISTED: 'Tên nhà cung cấp đã tồn tại.',
    SUPPLIER_BEING_USED: 'Nhà cung cấp đang được sử dụng.',
    DELIVERY_SERVICE_NOT_FOUND: 'Không tìm thấy đơn vị vận chuyển.',
    DELIVERY_SERVICE_EXISTED: 'Tên đơn vị vận chuyển đã tồn tại.',
    DELIVERY_SERVICE_BEING_USED: 'Đơn vị vận chuyển đang được sử dụng.',
    ORDER_STATUS_NOT_FOUND: 'Không tìm thấy trạng thái đơn hàng.',
    ORDER_STATUS_EXISTED: 'Tên trạng thái đơn hàng đã tồn tại.',
    ORDER_STATUS_BEING_USED: 'Trạng thái đơn hàng đang được sử dụng.',
    SUPPLIER_ADDRESS_EXISTED: 'Địa chỉ nhà cung cấp đã tồn tại.',
    SUPPLIER_CONTACT_EMAIL_EXISTED: 'Email liên hệ nhà cung cấp đã tồn tại.',
    SUPPLIER_CONTACT_PHONE_EXISTED: 'Số điện thoại liên hệ nhà cung cấp đã tồn tại.',
    DELIVERY_CONTACT_PHONE_EXISTED: 'Số điện thoại liên hệ đơn vị vận chuyển đã tồn tại.',
    CANNOT_DELETE_DEFAULT_ORDER_STATUS: 'Không thể xóa trạng thái đơn hàng mặc định.',
    ORDER_NOT_FOUND: 'Không tìm thấy đơn hàng.',
    CANNOT_UPDATE_TO_THIS_STATUS: 'Không thể chuyển đơn hàng sang trạng thái này.',
    INVENTORY_NOT_FOUND: 'Không tìm thấy sản phẩm tồn kho này.',
    INVENTORY_QUANTITY_NOT_ENOUGH: 'Sản phẩm tồn kho không đủ số lượng.',
    STORAGE_EXISTED: 'Tên kho đã tồn tại.',
    STORAGE_NOT_FOUND: 'Không tìm thấy kho.',
    STORAGE_BEING_USED: 'Kho đang được sử dụng.',
    STORAGE_TYPE_NOT_EXIST: 'Loại kho không tồn tại.',
    STATUS_TRANSITION_NOT_FOUND: 'Không tìm thấy hướng chuyển trạng thái.',
    STATUS_TRANSITION_EXISTED: 'Hướng chuyển trạng thái đã tồn tại.'
}

const SUCCESS_MESSAGES = {
    SIGN_IN_SUCCESSFULLY: 'Đăng nhập thành công.',
    SIGN_UP_SUCCESSFULLY: 'Đăng ký thành công.',
    REFRESH_TOKEN_SUCCESSFULLY: 'Làm mới token thành công.',
    DEACTIVATE_ACCOUNT_SUCCESSFULLY: 'Hủy kích hoạt tài khoản thành công.',
    REACTIVATE_ACCOUNT_SUCCESSFULLY: 'Kích hoạt tài khoản thành công.',
    RESET_PASSWORD_EMAIL_SENT: 'Email đặt lại mật khẩu đã được gửi.',
    GOOGLE_AUTH_SUCCESSFULLY: 'Xác thực Google thành công.',
    RESET_PASSWORD_SUCCESSFULLY: 'Đặt lại mật khẩu thành công.',
    CHANGE_PASSWORD_SUCCESSFULLY: 'Thay đổi mật khẩu thành công.',
    UPLOAD_IMAGE_SUCCESSFULLY: 'Tải ảnh lên thành công.',
    DELETE_IMAGE_SUCCESSFULLY: 'Xóa ảnh thành công.',
    UPDATE_USER_SUCCESSFULLY: 'Cập nhật người dùng thành công.',
    CREATE_ROLE_SUCCESSFULLY: 'Tạo vai trò thành công.',
    UPDATE_ROLE_SUCCESSFULLY: 'Cập nhật vai trò thành công.',
    DELETE_ROLE_SUCCESSFULLY: 'Xóa vai trò thành công.',
    DEACTIVATE_CUSTOMER_SUCCESSFULLY: 'Khóa tài khoản khách hàng thành công.',
    CREATE_CATEGORY_SUCCESSFULLY: 'Tạo danh mục thành công.',
    UPDATE_CATEGORY_SUCCESSFULLY: 'Cập nhật danh mục thành công.',
    DELETE_CATEGORY_SUCCESSFULLY: 'Xóa danh mục thành công.',
    CREATE_PRODUCT_SUCCESSFULLY: 'Tạo sản phẩm thành công.',
    UPDATE_PRODUCT_SUCCESSFULLY: 'Cập nhật sản phẩm thành công.',
    DELETE_PRODUCT_SUCCESSFULLY: 'Xóa sản phẩm thành công.',
    CREATE_PROMOTION_SUCCESSFULLY: 'Tạo chương trình khuyến mãi thành công.',
    UPDATE_PROMOTION_SUCCESSFULLY: 'Cập nhật chương trình khuyến mãi thành công.',
    DISABLE_PROMOTION_SUCCESSFULLY: 'Kết thúc chương trình khuyến mãi thành công.',
    CREATE_COUPON_SUCCESSFULLY: 'Thêm phiếu giảm giá thành công.',
    UPDATE_COUPON_SUCCESSFULLY: 'Cập nhật phiếu giảm giá thành công.',
    DISABLE_COUPON_SUCCESSFULLY: 'Khóa phiếu giảm giá thành công.',
    CREATE_DAMAGE_TYPE_SUCCESSFULLY: 'Thêm loại thiệt hại thành công.',
    UPDATE_DAMAGE_TYPE_SUCCESSFULLY: 'Cập nhật loại thiệt hại thành công.',
    DELETE_DAMAGE_TYPE_SUCCESSFULLY: 'Xóa loại thiệt hại thành công.',
    CREATE_STORAGE_TYPE_SUCCESSFULLY: 'Thêm loại kho thành công.',
    UPDATE_STORAGE_TYPE_SUCCESSFULLY: 'Cập nhật loại kho thành công.',
    DELETE_STORAGE_TYPE_SUCCESSFULLY: 'Xóa loại kho thành công.',
    CREATE_SUPPLIER_SUCCESSFULLY: 'Thêm nhà cung cấp thành công.',
    UPDATE_SUPPLIER_SUCCESSFULLY: 'Cập nhật nhà cung cấp thành công.',
    DELETE_SUPPLIER_SUCCESSFULLY: 'Xóa nhà cung cấp thành công.',
    CREATE_DELIVERY_SERVICE_SUCCESSFULLY: 'Thêm đơn vị vận chuyển thành công.',
    UPDATE_DELIVERY_SERVICE_SUCCESSFULLY: 'Cập nhật đơn vị vận chuyển thành công.',
    DELETE_DELIVERY_SERVICE_SUCCESSFULLY: 'Xóa đơn vị vận chuyển thành công.',
    CREATE_ORDER_STATUS_SUCCESSFULLY: 'Thêm trạng thái đơn hàng thành công.',
    UPDATE_ORDER_STATUS_SUCCESSFULLY: 'Cập nhật trạng thái đơn hàng thành công.',
    DELETE_ORDER_STATUS_SUCCESSFULLY: 'Xóa trạng thái đơn hàng thành công.',
    UPDATE_ORDER_SUCCESSFULLY: 'Cập nhật đơn hàng thành công.',
    UPDATE_INVENTORY_SUCCESSFULLY: 'Cập nhật sản phẩm tồn kho thành công.',
    CREATE_STORAGE_SUCCESSFULLY: 'Thêm kho thành công.',
    UPDATE_STORAGE_SUCCESSFULLY: 'Cập nhật kho thành công.',
    DELETE_STORAGE_SUCCESSFULLY: 'Xóa kho thành công.',
    TRACK_IMPORT_SUCCESSFULLY: 'Ghi nhận đơn nhập hàng thành công.',
    DISTRIBUTE_IMPORT_SUCCESSFULLY: 'Phân phối sản phẩm vào kho thành công.',
    CREATE_STATUS_TRANSITION_SUCCESSFULLY: 'Thêm hướng chuyển trạng thái thành công.',
    UPDATE_STATUS_TRANSITION_SUCCESSFULLY: 'Cập nhật hướng chuyển trạng thái thành công.',
    DELETE_STATUS_TRANSITION_SUCCESSFULLY: 'Xóa hướng chuyển trạng thái thành công.'
}

export const RES_MESSAGE_MAPPING = {
    ...ERROR_MESSAGES,
    ...SUCCESS_MESSAGES
}

export const getMappedMessage = (originalMessage: string) => {
    return RES_MESSAGE_MAPPING[originalMessage as keyof typeof RES_MESSAGE_MAPPING] ?? originalMessage
}
